/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CountriesCountryIdRouteImport } from './routes/countries.$countryId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CountriesCountryIdRoute = CountriesCountryIdRouteImport.update({
  id: '/countries/$countryId',
  path: '/countries/$countryId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/countries/$countryId': typeof CountriesCountryIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/countries/$countryId': typeof CountriesCountryIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/countries/$countryId': typeof CountriesCountryIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/countries/$countryId'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/countries/$countryId'
  id: '__root__' | '/' | '/countries/$countryId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CountriesCountryIdRoute: typeof CountriesCountryIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/countries/$countryId': {
      id: '/countries/$countryId'
      path: '/countries/$countryId'
      fullPath: '/countries/$countryId'
      preLoaderRoute: typeof CountriesCountryIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CountriesCountryIdRoute: CountriesCountryIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
